import { ClerkProvider } from "@clerk/nextjs";
import "@uploadthing/react/styles.css";
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import "~/styles/globals.css";
import { TopNav } from "./_components/topnav";


export const metadata: Metadata = {
  title: "CAT_AI",
  description: "Generated by CAT_AI",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};



export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en" className={GeistSans.variable}>
    <body className="font-sans flex flex-col gap-4">
      <TopNav />
      {children}
    </body>
      </html>
    </ClerkProvider>
  );
}